const canvas = document.querySelector("#HUD");

let ctx = canvas.getContext("2d");

ctx.moveTo(0, 0);
ctx.lineTo(200, 100);
ctx.stroke();


const listing = JSON.parse(localStorage.getItem("listing"))
  ? JSON.parse(localStorage.getItem("listing"))
  : [
    {name:'Arceus',
    atmosphere:'minimal',
    moons:'3',
    tempRange:'habitable',
    water:'liquid',
    size:'medium',
    population:'native',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download%20(11).png',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(1).png',

},
    {name:'Khannis',
    atmosphere:'adequate',
    moons:'1',
    tempRange:'habitable',
    water:'liquid',
    size:'medium',
    population:'colonial',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download.png',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(2).png',

},
    {name:'vellox',
    atmosphere:'ample',
    moons:'12',
    tempRange:'habitable',
    water:'liquid',
    size:'large',
    population:'native',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download%20(32).png',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(3).png',

},
    {name:'dreml',
    atmosphere:'none',
    moons:'11',
    tempRange:'low',
    water:'ice',
    size:'large',
    population:'native',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download%20(32).png',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(4).png',

},
    {name:'sx900t3',
    atmosphere:'none',
    moons:'0',
    tempRange:'extreme',
    water:'none',
    size:'small',
    population:'native',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download%20(12).png',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(5).png',

},
    {name:'rasenues',
    atmosphere:'ample',
    moons:'3',
    tempRange:'habitble',
    water:'liquid',
    size:'large',
    population:'colnial',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download%20(28).png',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(6).png',

},
    {name:'kretic',
    atmosphere:'minimal',
    moons:'2',
    tempRange:'habitble',
    water:'liquid',
    size:'large',
    population:'none',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(7).png',

},
    {name:'nikalum',
    atmosphere:'ample',
    moons:'3',
    tempRange:'habible',
    water:'liquid',
    size:'medium',
    population:'native',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download%20(27).png ',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(8).png',

},
    {name:'luxem',
    atmosphere:'minimal',
    moons:'2',
    tempRange:'low',
    water:'liquid',
    size:'medium',
    population:'native',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download%20(26).png',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(9).png',

},
    {name:'tsubo',
    atmosphere:'minmal',
    moons:'1',
    tempRange:'habitable',
    water:'liquid',
    size:'large',
    population:'native',
    populationURL:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/aliens/download%20(38).png',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(10).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(11).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(12).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(13).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(14).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(15).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(16).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(17).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(18).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(19).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(20).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(21).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download%20(22).png',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'https://raw.githubusercontent.com/Abdool-Zaid/propertyListing/main/assets/planetImages/download.png',

},
]