const canvas = document.querySelector("#HUD");

let ctx = canvas.getContext("2d");

ctx.moveTo(0, 0);
ctx.lineTo(200, 100);
ctx.stroke();


const listing = JSON.parse(localStorage.getItem("listing"))
  ? JSON.parse(localStorage.getItem("listing"))
  : [
    {name:'Arceus',
    atmosphere:'minimal',
    moons:'3',
    tempRange:'habitable',
    water:'liquid',
    size:'medium',
    population:'native',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
    {name:'',
    atmosphere:'',
    moons:'',
    tempRange:'',
    water:'',
    size:'',
    population:'',
    populationURL:'',
    image:'',

},
]